# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('edc_visit_schedule', '0002_auto_20160507_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipform',
            name='hostname_created',
            field=models.CharField(default='ckgathi', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershipform',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hostname_created',
            field=models.CharField(default='ckgathi', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitdefinition',
            name='hostname_created',
            field=models.CharField(default='ckgathi', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitdefinition',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
