# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 06:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_visit_schedule', '0003_auto_20180130_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdefinition',
            name='code',
            field=models.CharField(db_index=True, max_length=6, validators=[django.core.validators.MaxLengthValidator(6)], verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='visitdefinition',
            unique_together=set([('title', 'code')]),
        ),
    ]
