# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_visit_schedule', '0005_auto_20180206_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipform',
            name='content_type_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_content_type_map.ContentTypeMap'),
        ),
    ]
