# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_visit_schedule', '0006_auto_20180206_0739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitdefinition',
            unique_together=set([('title', 'code', 'instruction')]),
        ),
    ]
